#!/usr/bin/bash

# Handle button actions
case "$BLOCK_BUTTON" in
    1) wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle ;;
    2) pavucontrol & ;;
    3) wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle ;;
    4) wpctl set-volume --limit=1.0 @DEFAULT_AUDIO_SINK@ 5%+ ;;
    5) wpctl set-volume --limit=1.0 @DEFAULT_AUDIO_SINK@ 5%- ;;
esac

# In case of pipewire not being fully loaded (after boot)
max_retries=5
retry_count=0

while [ $retry_count -lt $max_retries ]; do
    mic_status=$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@ 2>&1)
    if echo "$mic_status" | grep -q "Translate ID error"; then
        # Increment retry count and wait before retrying
        retry_count=$((retry_count + 1))
        sleep 1
    else
        # Break the loop if no error
        break
    fi
done

if echo "$mic_status" | grep -q "[MUTED]"; then
    mic_icon=" "
else
    mic_icon=" "
fi

volume_status=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
if echo "$volume_status" | grep -q "[MUTED]"; then
    echo "^b#bf616a^^c#2e3440^ ${mic_icon}  ^b#2e3440^"
    exit
fi

volume_frac="$(echo "$volume_status" | cut -d' ' -f2)"
volume="$(echo "$volume_frac * 100 / 1" | bc)"

if [ -z "$volume" ]; then
    exit 1
fi

if [ "$volume" -gt 50 ]; then
    icon=" "
elif [ "$volume" -gt 20 ]; then
    icon=" "
else
    icon=""
fi

echo "^b#bf616a^^c#2e3440^ ${mic_icon}${icon} ^b#2e3440^^c#bf616a^ ${volume}%^b#2e3440^"